import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context";
import { Footer, Header } from "@/components";
import { Toaster } from "sonner";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Psicoterapia Individual",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/icon.png" />
      </Head>
      <AuthProvider>
        <body className={inter.className}>
          <Header />
          {children}
          <Toaster />
          <Footer />
        </body>
      </AuthProvider>
    </html>
  );
}
